#!/usr/bin/env bash

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    info line_break

    info "OS" distro
    info "Model" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "WM Theme" wm_theme
    info "CPU" cpu
#    info "GPU" gpu
    info "Memory" memory
    info "CPU Usage" cpu_usage
    info "Disk" disk
    info "Local IP" local_ip

    info line_break
    info cols
    info line_break
}


# Kernel


# Shorten the output of the kernel function.
# Values:   'on', 'off'
kernel_shorthand="on"


# Distro

# Shorten the output of the distro function
# Values:   'on', 'off', 'tiny'
distro_shorthand="off"

# Show/Hide OS Architecture.
# Values:  'on', 'off'
os_arch="on"


# Uptime

# Shorten the output of the uptime function
# Values:  'on', 'off', 'tiny'
uptime_shorthand="off"


# Shell

# Show the path to $SHELL
# Values:  'on', 'off'
shell_path="off"

# Show $SHELL version
# Values:  'on', 'off'
shell_version="on"


# CPU

# CPU speed type
# Values:  'current', 'min', 'max', 'bios',
speed_type="bios"

# Shorten the output of the CPU function
# Values:  'on', 'off', 'tiny', 'name', 'speed'
cpu_shorthand="off"

# CPU Speed
# Values:  'on', 'off'
cpu_speed="on"

# CPU Cores
# Values:  'logical', 'physical', 'off'
cpu_cores="off"

# CPU Temperature
# Values:  'on', 'off'
cpu_temp="off"


# GPU

# Enable/Disable GPU Brand
# Values:  'on', 'off'
gpu_brand="on"


# Resolution

# Display refresh rate next to each monitor
# Values:  'on', 'off'
refresh_rate="off"


# Gtk Theme / Icons / Font

# Shorten output of GTK Theme / Icons / Font
# Values:  'on', 'off'
gtk_shorthand="on"


# Enable/Disable gtk2 Theme / Icons / Font
# Values:  'on', 'off'
gtk2="on"

# Enable/Disable gtk3 Theme / Icons / Font
# Values:  'on', 'off'
gtk3="on"


# IP Address

# Website to ping for the public IP
# Values:  'url'
public_ip_host="http://ident.me"


# Song

# Print the Artist and Title on seperate lines
# Values:  'on', 'off'
# Flag:    --song_shorthand
song_shorthand="off"

# Text Colors

# Text Colors
# Values:   'distro', 'num' 'num' 'num' 'num' 'num' 'num'
colors=(distro)


# Text Options

# Toggle bold text
# Values:   'on', 'off'
bold="on"


# Underline character
underline_char="-"


# Color Blocks

# Color block range
# Values:   'num'
start=0
end=7

# Toggle color blocks
# Values:   'on', 'off'
color_blocks="on"

# Color block width in spaces
# Values:   'num'
block_width=3

# Color block height in lines
# Values:   'num'
block_height=1



# Progress bar length in spaces
# Values:   'num'
bar_length=15

# Progress bar colors
# Values:   'distro', 'num'
bar_color_elapsed="distro"
bar_color_total="distro"


# Info display
# Values:  'bar', 'infobar', 'barinfo', 'off'
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"


# Image Options

# Image Source
# Values:   'ascii', 'wallpaper', '/path/to/img', '/path/to/dir/', 'off'
image_source="ascii"

# Thumbnail directory
# Values:  'dir'
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"

# w3m-img path
w3m_img_path="/usr/lib/w3m/w3mimgdisplay"

# Crop mode
# Values:   'normal', 'fit', 'fill'
crop_mode="normal"

# Crop offset
# Values:   'northwest', 'north', 'northeast', 'west', 'center'
#           'east', 'southwest', 'south', 'southeast'
crop_offset="center"

# Image size
# Values:  'auto', '00px', '00%', 'none'
image_size="auto"

# Ggap between image and text
# Values:  'num', '-num'
gap=3

# Image offsets
# Values:  'px'
yoffset=0
xoffset=0

# Image background color
# Values:  'color', 'blue'
background_color=


# Ascii Options

# Default ascii image to use
# Values:  'distro', '/path/to/ascii_file'
ascii="distro"

# Ascii distro
# Values:  'auto', 'distro_name'
ascii_distro="auto"

# Ascii Colors
# Values:   'distro', 'num' 'num' 'num' 'num' 'num' 'num'
ascii_colors=(distro)

# Logo size
# Values:  'normal', 'small'
ascii_logo_size="normal"

# Bold ascii logo
# Values:  'on', 'off'
ascii_bold="on"


# Scrot Options

# Whether or not to always take a screenshot
# Values:  'on', 'off'
scrot="off"

# Screenshot Program
# Values:  'auto' 'cmd -flags'
scrot_cmd="auto"

# Screenshot Directory
# Values:  'dir'
scrot_dir="$HOME/Pictures/"

# Screenshot Filename
# Values:  'string'
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"

# Image upload host
# Values:  'imgur', 'teknik'
image_host="teknik"


# Config Options

# Enable/Disable config file
# Values:  'on', 'off'
config="on"

# Path to custom config file location
# Values:  '/path/to/config'
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"

